export const RESET_REDIRECT = '@@global/RESET_REDIRECT'

export const FETCHING_CLASS_TYPES = '@@classTypes/FETCHING_CLASS_TYPES'
export const GET_CLASS_TYPES = '@@classTypes/GET_CLASS_TYPES'

export const FETCHING_CLASS_TYPE = '@@classType/FETCHING_CLASS_TYPE'
export const GET_CLASS_TYPE = '@@classType/GET_CLASS_TYPE'
export const EDIT_CLASS_TYPE = '@@classType/EDIT_CLASS_TYPE'
export const EDIT_CLASS_TYPE_DESCRIPTION = '@@classType/EDIT_CLASS_TYPE_DESCRIPTION'
export const UPDATE_CLASS_TYPE = '@@classType/UPDATE_CLASS_TYPE'
export const CLEAR_CLASS_TYPE = '@@classType/CLEAR_CLASS_TYPE'
export const CREATE_CLASS_TYPE = '@@classType/CREATE_CLASS_TYPE'
export const DELETE_CLASS_TYPE = '@@classType/DELETE_CLASS_TYPE'

export const FETCHING_LOCATIONS = '@@classType/FETCHING_LOCATIONS'
export const GET_LOCATIONS = '@@locations/GET_LOCATIONS'

export const FETCHING_LOCATION = '@@location/FETCHING_LOCATION'
export const GET_LOCATION = '@@location/GET_LOCATION'
export const CLEAR_LOCATION = '@@location/CLEAR_LOCATION'
export const CREATE_LOCATION = '@@location/CREATE_LOCATION'
export const DELETE_LOCATION = '@@location/DELETE_LOCATION'
export const EDIT_LOCATION = '@@location/EDIT_LOCATION'
export const UPDATE_LOCATION = '@@location/UPDATE_LOCATION'

export const FETCHING_ROOMS = '@@rooms/FETCHING_ROOMS'
export const GET_ROOMS = '@@rooms/GET_ROOMS'

export const CLEAR_ROOM = '@@room/CLEAR_ROOM'
export const CREATE_ROOM = '@@room/CREATE_ROOM'
export const DELETE_ROOM = '@@room/DELETE_ROOM'
export const FETCHING_ROOM = '@@room/FETCHING_ROOM'
export const GET_ROOM = '@@room/GET_ROOM'
export const EDIT_ROOM = '@@room/EDIT_ROOM'
export const UPDATE_ROOM = '@@room/UPDATE_ROOM'

export const GET_ORGANIZATIONS = '@@organizations/GET_ORGANIZATIONS'

export const FETCHING_USERS = '@@users/FETCHING_USERS'
export const GET_USERS = '@@users/GET_USERS'
export const GET_MORE_USERS = '@@users/GET_MORE_USERS'

export const FETCHING_USER = '@@user/FETCHING_USER'
export const GET_USER = '@@user/GET_USER'
export const CREATE_USER = '@@user/CREATE_USER'
export const DELETE_USER = '@@user/DELETE_USER'
export const EDIT_USER = '@@user/EDIT_USER'
export const EDIT_USER_DESCRIPTION = '@@user/EDIT_USER_DESCRIPTION'
export const UPDATE_USER = '@@user/UPDATE_USER'

export const FETCHING_CLASS_EVENTS = '@@classEvents/FETCHING_CLASS_EVENTS'
export const GET_CLASS_EVENTS = '@@classEvents/GET_CLASS_EVENTS'

export const ADDED_STUDENT = '@@classEvent/ADDED_STUDENT'
export const REMOVED_STUDENT = '@@classEvent/REMOVED_STUDENT'
export const FETCHING_CLASS_EVENT = '@@classEvent/FETCHING_CLASS_EVENT'
export const GET_CLASS_EVENT = '@@classEvent/GET_CLASS_EVENT'
export const CREATE_CLASS_EVENT = '@@classEvent/CREATE_CLASS_EVENT'
export const DELETE_CLASS_EVENT = '@@classEvent/DELETE_CLASS_EVENT'
export const EDIT_CLASS_EVENT = '@@classEvent/EDIT_CLASS_EVENT'
export const UPDATE_CLASS_EVENT = '@@classEvent/UPDATE_CLASS_EVENT'

export const GET_PRODUCT = '@@products/GET_PRODUCT'
export const FETCHING_PRODUCT = '@@products/FETCHING_PRODUCT'
export const FETCHING_PRODUCTS = '@@products/FETCHING_PRODUCTS'
export const GET_PRODUCTS = '@@products/GET_PRODUCTS'
export const GET_MORE_PRODUCTS = '@@products/GET_MORE_PRODUCTS'
export const CREATE_PRODUCT = '@@products/CREATE_PRODUCT'
export const DELETE_PRODUCT = '@@products/DELETE_PRODUCT'
export const UPDATE_PRODUCT = '@@products/UPDATE_PRODUCT'
export const EDIT_PRODUCT = '@@products/EDIT_PRODUCT'
export const EDIT_PRODUCT_DESCRIPTION = '@@products/EDIT_PRODUCT_DESCRIPTION'
